### PR TITLE
add comment on this README.md

### PR DESCRIPTION
**Pull request by ChoirulA**

### CODE REVIEW

**Comment by root-ansh** [comment]
hi @ChoirulA  , I appreciate your contribution , but i would be glad if you rather make a more productive change.
The disclaimer feels correct for now , and your addition will break the meaning of it. Try adding a picture in main  repo or correct any spelling mistakes in readme, they are better places to contribute!

**Comment by ChoirulA** [comment]
oh i'm so sorry about that, but i'm a newbie, and i just follow my friend

Pada tanggal Sel, 1 Okt 2019 pukul 16.01 Ansh Sachdeva <
notifications@github.com> menulis:

**Comment by root-ansh** [comment]
@ChoirulA  no worries. Try to follow the steps written in readme and let me know if you find any problem

**Comment by ChoirulA** [comment]
Okee, once agains i’m so sorry 🙏🏻

**Pull request closed without merging**
